# Generated by Django 4.2.3 on 2024-02-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=50)),
                ("action_code", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Turtle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("status", models.BooleanField()),
                ("position", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SentCommands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "comand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controller.command",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controller.turtle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_text", models.TextField()),
                ("timestamp", models.DateTimeField()),
                (
                    "turtle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controller.turtle",
                    ),
                ),
            ],
        ),
    ]
