# Generated by Django 4.2.3 on 2024-03-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="turtle",
            name="ComputerID",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="turtle",
            name="worldID",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
