# Generated by Django 4.2.3 on 2024-03-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0004_token_alter_turtle_id_alter_turtle_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turtle",
            name="computerID",
            field=models.IntegerField(default=0),
        ),
    ]
