# Generated by Django 4.2.3 on 2024-03-05 04:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0005_alter_turtle_computerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="link",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
