# Generated by Django 4.2.3 on 2024-03-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0007_remove_token_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turtle",
            name="position",
        ),
    ]
