# Generated by Django 5.0.3 on 2024-03-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_remove_turtle_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turtle',
            name='status',
        ),
    ]
